trigger:
    branches:
      include:
      - master
    paths:
      exclude:
      - CHANGELOG.md

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self
    clean: true
    persistCredentials: true

  - task: Bash@3
    name: Release
    env:
      STAGING_PATH: $(Build.ArtifactStagingDirectory)
      LOCAL_PATH: $(Build.Repository.LocalPath)
      DOCKER_HUB_PASSWORD: $(DOCKER_HUB_PASSWORD)
    inputs:
      targetType: 'inline'
      script: |
        cp eapp.mjs package.json $STAGING_PATH
        time curl -L https://github.com/Elders/blob/releases/download/SemRel-01/node_modules.tar.gz | tar mx -I pigz
        time npx semantic-release --no-ci
        set

  - task: PublishPipelineArtifact@1
    condition: and(eq(variables['newVer'], 'yes'), succeeded())
    inputs:
      targetPath: 'ci'
      artifact: 'manifest'
      publishLocation: 'pipeline'
